name: mypy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.x
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install setuptools==67.8.0
        python -m pip install --upgrade pip!=22.1.*
        python -m pip install --upgrade mypy
        python -m pip install --upgrade pandas-stubs
        python -m pip install --upgrade types-appdirs
        python -m pip install --upgrade wheel pytest numpy flit
        python -m pip install --upgrade appdirs click happi pandas bluesky suitcase-csv matplotlib
        python -m pip install . --no-build-isolation
    - name: Run mypy
      run: |
        mypy auto_rxn
