# This workflows will upload a Python Package when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install setuptools==67.8.0
        python -m pip install --upgrade pip!=22.1.*
        python -m pip install --upgrade build twine
        python -m pip install --upgrade wheel pytest numpy
        python -m pip install --upgrade appdirs click happi pandas bluesky suitcase-csv matplotlib
        python -m pip install . --no-build-isolation
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build .
        twine upload dist/*
